### ISSUE TITLE
todo: 한 번에 끝내는 프론트엔드 개발 초격차 패키지 Online 수강

### ISSUE THREAD

**Issue by DeukHan** [DeukHan/Study-Web#11]
- [x] Part 1. HTML/CSS/JS로 만드는 스타벅스 웹사이트 
- [ ] Part 2. Git을 활용한 버전관리 
- [ ] Part 3. JavaScript Essentials 
- [ ] Part 4. JavaScript Level up 
- [ ] Part 5. TypeScript Essentials 
- [ ] Part 6. SCSS 
- [ ] Part 7. CSS 프레임워크 BootStrap 
- [ ] Part 8. Bundler 
- [ ] Part 9. Vue.js 
- [ ] Part 10. React 로 쇼핑몰 만들기 
- [ ] Part 11. Redux로 상태관리하기 
- [ ] Part 12. React로 나의 책장 만들기 
- [ ] Part 13. mobX로 상태관리하기 
- [ ] Part 14. GraphQL 맛보기  
- [ ] Part 15. Next.js로 블로그 만들기 
- [ ] Part 16. Svelte

https://fastcampus.co.kr/

패스트캠퍼스 온라인 교육 완료를 목표로 하고있습니다.
@kimkmin357 @dev-heeseok

**Comment by dev-heeseok** [comment]
강의 들으면서 좋은 내용이 있으면 공유 해주세요 😃

**Comment by dev-heeseok** [comment]
@DeukHan 
주말에 열심히 하던데 커피한잔하면서 같이 공유 부탁드려요 :D
